import type { Metadata } from "next";
import { RaikouProvider } from "@raikou/system";
import { ToastContainer } from "react-toastify";
import { getPageSession } from "@golfcart/auth";
import AuthProvider from "./authProvider";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getPageSession();

  return (
    <html lang="en">
      <body>
        <>
          {/* <AuthProvider session={session}> */}
          <RaikouProvider>{children}</RaikouProvider>
          <ToastContainer autoClose={1000} />
          {/* </AuthProvider> */}
        </>
      </body>
    </html>
  );
}
